[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "entropy"
version = "1.0.0"

[tool.setuptools]
py-modules = []

[project.scripts]
leitner = "entropy:main"
