[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "entropy"
version = "1.0"
description = "create installer packages"

[project.scripts]
entropy = 'entropy:main'